import '../styles/globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '../components/header/Header';
import { Footer } from '../components/footer/Footer';
import { Providers } from '@/store/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Gscore',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <main className={`main ${inter}`}>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
