import '../styles/globals.scss';
import type { Metadata } from 'next';
import Header from '../components/modules/header/Header';
import { Footer } from '../components/modules/footer/Footer';
import { Providers } from '@/store/provider';
import localFont from 'next/font/local';

const greatVibes = localFont({
  src: './fonts/THICCCBOI-Medium.ttf',
  variable: '--font-THICCCBOI',
});

export const metadata: Metadata = {
  title: 'Gscore',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={greatVibes.className} lang="en">
      <body>
        <Providers>
          <Header />
          <main className={`main`}>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
